[platformio]
default_envs = nrf24-diagnostic

[env:nrf24-diagnostic]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../lib
build_flags =
    -std=gnu++17
    -D OBSIDIA_NRF24_SCLK_GPIO=-1
    -D OBSIDIA_NRF24_MISO_GPIO=-1
    -D OBSIDIA_NRF24_MOSI_GPIO=-1
    -D OBSIDIA_NRF24_CSN_GPIO=-1
    -D OBSIDIA_NRF24_CE_GPIO=-1
    -D OBSIDIA_NRF24_SPI_HZ=1000000
build_unflags = -std=gnu++11
