[platformio]
default_envs = st7735-diagnostic

[env:st7735-diagnostic]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../lib
build_flags =
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D ST7735_BLACKTAB=1
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160
    -D TFT_MISO=-1
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=9
    -D TFT_RST=14
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D LOAD_GLCD=1
    -D SPI_FREQUENCY=10000000
    -D SPI_READ_FREQUENCY=1000000
    -D TOUCH_CS=-1
